### PR TITLE
Documentation Fix: Language detection does not work

### PR DESCRIPTION
**Pull request by amenk**
We already have the root language, so use ->language

### CODE REVIEW

**Comment by aschempp** [comment]
these parameters are actually identical, the `language` is just for backwards compatibility reasons…

**Comment by amenk** [comment]
interesting... in my case it was not working with rootLanguage (null) but
with language. (actual language). In Contao 3.5

**Comment by aschempp** [comment]
interesting, that might actually be a Contao bug because the properties are not set for a root page.

**Comment by fritzmg** [comment]
Indeed the `root…` properties are only set for non-root pages: https://github.com/contao/core/blob/3.5.27/system/modules/core/models/PageModel.php#L862
It has been this way since the inception of the `root…` properties though.

**Comment by aschempp** [comment]
We just discussed this in the Contao call, and what you say seems not correct. Are you on the latest Contao version?

**Comment by fritzmg** [comment]
But it is correct:
```php
if ($objParentPage !== null && $objParentPage->type == 'root')
{
    …
    $this->rootLanguage = $objParentPage->language;
    …
}
```
`$this->rootLanguage` is only set, if `$objParentPage` is not `null`. And `$objParentPage` will be `null` if the `type` of the page is `'root'`. So if your page object is of type `'root'` , you must use `$objPage->language` instead of `$objPage->rootLanguage`.

**Comment by aschempp** [comment]
> And $objParentPage will be null if the type of the page is 'root'

Not true: https://github.com/contao/core/blob/3.5.27/system/modules/core/models/PageModel.php#L789

**Comment by bytehead** [comment]
Can confirm the issue. But it's not only documentation, the `ChangelanguageNavigationEvent-> navigationItem->targetPage` seems to be wrong as well.

**Comment by aschempp** [comment]
I'd like to find out why this happens instead of just patching something… Looks like a core bug to me, so we should investigate that beforehand.

**Comment by fritzmg** [comment]
> Not true: https://github.com/contao/core/blob/3.5.27/system/modules/core/models/PageModel.php#L789

Hm, indeed. I noticed this issue somewhere else as well and thought this was (sort of) intended. I'll investigate this again when I have the chance.

**Comment by aschempp** [comment]
Any update on the issue?

**Comment by fritzmg** [comment]
Looking at the code of changelanguage, `->rootLanguage` is not available because `->loadDetails()` is never called on the loaded root pages.

**Comment by jankout** [comment]
I can confirm this behaviour.

**Comment by aschempp** [comment]
Changed in a43ee592458b712750e5184fb93118af90ff07fe

**Pull request closed without merging**
