### PR TITLE
Remove auto_items from URL see #167

### PR DESCRIPTION
**Pull request by c4y**

### CODE REVIEW

**Comment by aschempp** [comment]
Thanks for your pull request!
Is there a situation where we do want the `auto_item` parameters (like `events`, `items`) to remain in the URL? Otherwise we can simply skip all of `$GLOBALS['TL_AUTO_ITEM']` in the URL, what do you think?

**Comment by c4y** [comment]
That was my first thought and had solved it that way. I do not remember why I rewrote it. But I think by now that we can just remove the auto_items as suggested by you. Should I make a new pull request?

**Comment by aschempp** [comment]
You can simply update the existing pull request 😉

**Comment by c4y** [comment]
I think i have made some mistakes? I accidentally deleted the file with commit f7ac973. And as i removed the unnecessary changes, i created several commits. Can you help?

**Comment by richardhj** [comment]
Do you want to start from scratch?
Then do a 
`git reset --hard 764854f733a3373ecf9be2d54518311bf2581f5a` (this will reset all your changes)

Or check https://ohshitgit.com/.

**Comment by c4y** [comment]
As i mentioned in #167. If you have an event for "de", but not for "en", then Changelanguage removes the alias for the "en" event, so you will see the list. But if you use Changelanguage as InsertTag in a Module inside the PageLayout it does not work and generates a non existing link (404).

**Comment by aschempp** [comment]
das würde aber doch bedeuten dass ein korrekter Link auch nicht geladen wird? Bzw. was wenn ein Element auf der anderen Sprache mit demselben Alias existiert?

**Pull request closed without merging**
