### PR TITLE
Update composer.json

### PR DESCRIPTION
**Pull request by katgirl**
Change about to install in Contao 3.5.2

### CODE REVIEW

**Comment by aschempp** [comment]
Why is this be necessary?

**Comment by Toflar** [comment]
Because you cannot install it with 3.5.2 otherwise? :D It should be changed to `^3.2` though, I think.

**Comment by aschempp** [comment]
Does "3.5" not equal "3.5.*" ?

**Comment by katgirl** [comment]
yes, you can't install under 3.5.*

**Comment by davidmaack** [comment]
You put <= 3.5 in the composer.json, so composer will translate this to 3.5.0.0

```
Problem 1
    - The requested package contao/core == 3.5.0.0 could not be found.
```

**Comment by Toflar** [comment]
Fixed and released in 01d59a08198f21a5d46b84e3d2b8a3e370a6681f.

**Pull request closed without merging**
