### PR TITLE
Fixed a bug sql

### PR DESCRIPTION
**Pull request by luger95**
Change languageMain=? in languageMain IN ?

### CODE REVIEW

**Comment by aschempp** [comment]
That does not make sense to me. An SQL `IN()` search with only one value is exactly the same as an equal-comparison. Can you explain the original problem?

**Comment by luger95** [comment]
On my web site the query is done on multiple values.

**Comment by aschempp** [comment]
That can't be true if you look at the SQL query. Or do you mean `$mainLanguageID` contains a comma separated list of values in your case?

**Comment by luger95** [comment]
$mainLanguageID contains multiple values.
My website is in several languages, with several news archives bound between itself with change language

**Comment by aschempp** [comment]
I'm sorry but I don't understand.

 1. How is newslanguage related to this? The core changelanguage script is only about pages.
 2. There cannnot be a relation where multiple root pages are linked with multiple others. There is always one master and then there are multiple slaves. The slaves will always have `languageMain` ID of the master… ?

**Comment by aschempp** [comment]
Any feedback on the topic?

**Comment by luger95** [comment]
I agree on the logic and this is the one I use. But I was faced with missed redirects. So I searched the problem and I found that $mainLanguageID contained several values. I have not found out why.

**Comment by aschempp** [comment]
This must be due to a misconfiguration or some incorrect database values. That sometimes happens after e.g. copying a page tree. But it should not be supported…

Please let me know if you could find out why it happens, but I'll have to close the PR until then.

**Pull request closed without merging**
