### PR TITLE
Replicate languages (de -> de_DE, de_CH, de_AT)

### PR DESCRIPTION
**Pull request by amenk**

### CODE REVIEW

**Comment by aschempp** [comment]
I'm sorry, but this can't be right? Why would you add a link for every local language?

**Comment by aschempp** [comment]
Can you explain the intentions?

**Comment by amenk** [comment]
The reason is related SEO ... to express, taht the content is also available in Swiss German, Austrian German ...

**Comment by aschempp** [comment]
Which is not correct, because the content is only available in one version? 

Also, be aware that `de_CH` is **NOT** swiss german! `de_CH` means a standard german content for Switzerland, whereas *swiss german* would be written differently. There is no two character code for swiss german (see https://de.wikipedia.org/wiki/Schweizerdeutsch), so you actually can't correctly use that in Contao… (the formally correct code would be `gsw` or `gsw_CH`).
Also see https://github.com/contao/core-bundle/issues/233 on the topic.

**Comment by amenk** [comment]
Thanks for the clarification with the swiss German.
As I understood it, the German content we have, is also valid for switzerland and austria ... that is why it seems to make sense to provide those additional tags.
But I asked our SEO people to clarify this.

**Comment by k-webdesign** [comment]
It's a similar thing I asked for in issue 64. I tried it in some websites and noticed the SEO visibility highly raised after implementing this. Would be a nice feature, but you should have the choice in the backend whether to use or not, maybe by a checkbox.

**Comment by aschempp** [comment]
I'm closing this because I don't think it should be generally implemented. In ChangeLanguage v3 you can accomplish this by adjusting the template (see FAQ section of [the new manual](https://github.com/terminal42/contao-changelanguage/blob/release/3.0.0/README.md))

**Pull request closed without merging**
