### PR TITLE
small improvement to show the correct page title after Event Callback

### PR DESCRIPTION
**Pull request by markusmilkereit**
targeted at news, events, faq and article links - new abstract method and implementation in all Event types.

### CODE REVIEW

**Comment by aschempp** [comment]
can you please explain some more what this is supposed to do?

**Comment by markusmilkereit** [comment]
Sure :) The core logic of changelanguage handles the URL for different language(s), that works nicely. But you also have logic in there to update the title of the link. That works well for (direct) pages, because they have their own title. But for news, even and all the other detail page with autoalias pages, you get the title from the detail page, not the item.

So I extended the logic a little bit, and update not just the URL, but also the title of the item - so it can show nicely in the hover tooltip. On this page: https://www.vonheldenundgestalten.de/blog/diversity-marketing-welche-farbe-hat-eigentlich-reis.html you get a real hover tooltip of the connected english version of the news entry:
image
Before the PR it would only show "Blog Detail page" (which is not very helpful)

**Comment by aschempp** [comment]
I have attempted a different implementation in cd46674c236c9b7900da52fce8e3f6ce4d782080. Can you please check if the latest `main` branch works for you?

**Comment by markusmilkereit** [comment]
reading the code it seams incomplete - only FAQs have the new `NavigationHandlerInterface`, which is needed to trigger the new logic for titles. Which is good because News and Events would execute `updateNavigation`, when the target method should be `handleNavigation` - I guess you rewrote the logic along the way? :)

I test-installed it on our development version as dev-main anyway, but yeah, does not work.

When I'm giving News and Events the same (new) logic that the FAQ have, then it works beautifully:

image

**Comment by aschempp** [comment]
You're absolutely right, I totally forgot to fix those listeners. Good to have another pair of 👀 looking at it! I have updated the `main` branch, can you please check again?

**Comment by markusmilkereit** [comment]
Yes works, installed dev-main on our dev page, and then live - all good so far (only tested news, but the logic is almost the same everywhere) - release? :)

**Comment by aschempp** [comment]
Released as 3.6.0 then. Thanks for your input and PR! 😊

**Pull request closed without merging**
