### PR TITLE
Allow hiding a link by via hook

### PR DESCRIPTION
**Pull request by amenk**
We need that here: https://github.com/iMi-digital/imi_mm_changelanguage/blob/master/contao/classes/Observer.php :)

### CODE REVIEW

**Comment by aschempp** [comment]
Even though the implementation might work, it must be wrong. Because the same `$arrParams` is passed for every root page, and if you hide a link for one root it means it will be hidden for all following roots.

Can you give me a real-world example for this? Then we might come up with a better solution…

**Comment by amenk** [comment]
I use it in there:

https://github.com/iMi-digital/imi_mm_changelanguage/blob/master/contao/classes/Observer.php

**Comment by amenk** [comment]
Would it help to `unset($arrParams['hide'])` before the observer call?

**Comment by amenk** [comment]
What do you think @aschempp ? Or is  there another way to fix this?

**Comment by amenk** [comment]
*bump*

**Comment by aschempp** [comment]
I'm sorry but currently I don't have time to fix this. Be aware that your custom patch will work until a new version is released, which should not be the case without handling this.

**Comment by amenk** [comment]
Yes sure. But maybe to can give a hint. I am willing to fix this. Somehow I did not fully understand what you wrote. If you tell me that "Would it help to unset($arrParams['hide']) before the observer call?" does not help I will dive deeper in it, otherwise I will update my PR.

**Comment by aschempp** [comment]
I guess the correct thing would be to add `$addToNavigation` as a new parameter which can be changed using referencing.

**Comment by amenk** [comment]
But when I add a parameter to the callback, this would break BC (generate a warning). So I think unsetting / setting hide to false before each call of the hook would have the same effect?

**Comment by aschempp** [comment]
Why should a new parameter add an error?

**Comment by amenk** [comment]
Okay you are right. I changed my commit.

**Comment by aschempp** [comment]
Thanks. Did you test it on your system (where you previously implemented the other option)?

Also, the comment does not make sense to me, and the line break does not follow PRS-2. Can you please update that?

**Comment by amenk** [comment]
Fixed.
Yes I tested it. The change is already in the latest version of https://github.com/iMi-digital/imi_mm_changelanguage

**Comment by amenk** [comment]
Any chance to get that merged?

**Comment by aschempp** [comment]
Merged in 01c0183bda9cc7c56bd9ada2fa1f201d72a4eda7

**Comment by amenk** [comment]
@aschempp Ähm, wieso wurde das denn nicht in den master gemergt??

**Comment by Toflar** [comment]
Weil der Hotfix noch nicht veröffentlicht wurde. /cc @aschempp

**Comment by amenk** [comment]
Ah okay. Und was ist mit develop?

Dort ist irgendwie auch alles auskommentiert ??

https://github.com/terminal42/contao-changelanguage/blob/develop/src/Terminal42/ChangeLanguage/Module/ChangeLanguage.php

**Comment by Toflar** [comment]
Ja eben, der enthält die potenziell neue Version. Deswegen ist es ja der develop.

**Pull request closed without merging**
