### PR TITLE
Use pageTitle as title

### PR DESCRIPTION
**Pull request by havutcuoglu**
Use pageTitle as title
See: https://github.com/terminal42/contao-changelanguage/issues/179

### CODE REVIEW

**Comment by fritzmg** [comment]
You should combine https://github.com/terminal42/contao-changelanguage/pull/181 into this PR.

**Comment by havutcuoglu** [comment]
How can I combine it?

**Comment by fritzmg** [comment]
> How can I combine it?

You already did it ;). You can now close #181.

**Comment by havutcuoglu** [comment]
Yes, I have it and I did it 😄

**Comment by aschempp** [comment]
Thank you @havutcuoglu !

**Pull request merged**
